server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_consumer
    username: 'postgres'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database: postgresql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: consumer-service

broker:
  queue-direct-uno: my-queue-uno
