server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_producer
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_FROM}
    password: ${PASSWORD_APPLICATION_GOOGLE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: producer-topic-service

broker:
  exchange-topic-uno: my-topic-exchange-uno
  routing-key-dos: my.routing.key.*
  queue-direct-uno: my-queue-uno